apiVersion: v1
kind: Namespace
metadata:
  name: k8s-program

---

apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: user-app-pod
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: user-app-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: user-app-pod
        owner: naziasultan
    spec:
      containers:
        - name: user-container
          image: naziasultan/user:1.0.0
          ports:
            - containerPort: 8080

---


apiVersion: v1
kind: Service
metadata:
  name: posts
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: post-app-pod
  ports:
    - protocol: "TCP"
      port: 8083
      targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: post-app-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: post-app-pod
        owner: naziasultan
    spec:
      containers:
        - name: post-container
          image: naziasultan/posts:1.0.0
          ports:
            - containerPort: 8080


---


apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: k8s-program
spec:
  type: LoadBalancer
  selector:
    app: mysql-pod
  ports:
    - protocol: "TCP"
      port: 3306
      targetPort: 3306

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: k8s-program
spec:
  selector:
    matchLabels:
      app: mysql-pod
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql-pod
        owner: naziasultan
    spec:
      containers:
        - name: mysql-container
          image: naziasultan/mysql:8.0.32
          ports:
            - containerPort: 3306

